server/apps/partnership/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r"software/(?P<pk>\d+)/", views.SoftwareDetail.as_view(), name="software_detail"
    ),
    url(r"software/search/", views.SoftwareSearch.as_view(), name="software_search"),
    url(r"software/", views.SoftwareList.as_view(), name="software"),
    url(
        r"investors/(?P<slug>[-a-zA-Z0-9_]+)",
        views.ForInvestorsDetailView.as_view(),
        name="investors-details",
    ),
    url(r"api/", views.ForInvestorsListAPIView.as_view(), name="for-investors-api"),
    url(
        r"interested-request/(?P<pk>[0-9]+)/",
        views.InterestedRequestAPIView.as_view(),
        name="for-investors-interested-request",
    ),
    url(
        r"investors/",
        views.ForInvestorsTemplateView.as_view(),
        name="for-investors-list",
    ),
    url(
        r"send-request/", views.CreatePartnershipRequest.as_view(), name="send-request"
    ),
]

server/marketplace/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf import settings
from rest_framework.routers import DefaultRouter

from accounts import views as accounts_views
from user_filter_api.views import SearchFilterViewSet
from user_settings import views as settings_views

router = DefaultRouter()
router.register("filters", SearchFilterViewSet)

urlpatterns = [
    path("accounts/", include("accounts.urls")),
    path("core/", include("core.urls")),
    path("company/", include("company.urls")),
    path("chat/", include("chat.urls")),
    url("", include("social_django.urls", namespace="social")),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    # set url for accounts app view here because accounts app uses as App hook
    path(
        "reset/<uidb64>/<token>/",
        accounts_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "activate/<uidb64>/<token>/",
        accounts_views.ActivateAccountView.as_view(),
        name="activate_account",
    ),
    path(
        "get-secret-key/<uidb64>/<token>/",
        accounts_views.GetSecretKeyView.as_view(),
        name="get-secret-key",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "invite/<uid>/",
        settings_views.new_invitee_password_view,
        name="create_invitee_password",
    ),
    path("invite/", settings_views.create_new_invitee_view, name="save_invitee"),
    path(
        "invite/<uid>/<pid>/<token>/", settings_views.save_invitee, name="save-invitee"
    ),
    path("django-admin/", admin.site.urls),
    path("api/v1/chats/", include("chat_api.urls")),
    path("api/v1/accounts/", include("accounts_api.urls")),
    path("api/v1/documents/", include("documents_api.urls")),
    path("api/v1/projects/", include("projects_api.urls")),
    path("api/v1/", include(router.urls)),
    path("", include("cms.urls")),
]

# urlpatterns += patterns(
#     prefix_default_language=False)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/apps/partnership/models.py
# Create your models here.
from django.db import models

from core.models import AbstractUserRequest, WatchableMixin

INVESTOR_AMOUNTS = (
    (0, "10k - 50k"),
    (1, "50k - 100k"),
    (2, "100k - 500k"),
    (3, "500k - 1kk"),
)

OPERATING_SYSTEMS = (
    (0, "Windows"),
    (1, "Mac"),
    (2, "Linux"),
)

LICENSE_TYPE = (
    (0, "Standard License"),
    (1, "Extended License"),
    (2, "Multi License"),
)


class ForInvestor(WatchableMixin):
    """VR
    ForInvestor article model for Partnership view
    """

    name = models.CharField(max_length=150)
    slug = models.SlugField(max_length=255, unique=True, null=True, blank=True)
    industry = models.ForeignKey(
        "project.Industry", on_delete=models.CASCADE, related_name="for_investors"
    )
    text = models.TextField()
    excerpt = models.TextField(default="")
    image = models.ImageField(upload_to="for_investor", blank=True, null=True)
    amount = models.SmallIntegerField(choices=INVESTOR_AMOUNTS)
    interested_requests = models.PositiveIntegerField(default=0)

    def get_absolute_url(self):
        from django.urls import reverse

        return reverse("investors-details", args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = "-".join(self.name.split(" "))

        return super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.name}"


class Software(models.Model):
    name = models.CharField(max_length=150)
    license = models.SmallIntegerField(choices=LICENSE_TYPE)
    short_description = models.TextField()
    description = models.TextField()
    size = models.CharField(max_length=50, blank=True, null=True)
    image = models.ImageField(upload_to="software_images/", blank=True, null=True)
    logo = models.ImageField(upload_to="software_logo/", blank=True, null=True)
    link = models.CharField(max_length=255, null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class SoftwareFile(models.Model):
    software = models.ForeignKey(
        "Software", related_name="software_file", on_delete=models.CASCADE
    )
    os = models.SmallIntegerField(choices=OPERATING_SYSTEMS)
    file = models.FileField(upload_to="software/")


class PartnershipRequest(AbstractUserRequest):
    pass

server/apps/partnership/views.py
from core.mixins import VueTemplateMixin
from core.serializers import NameSlugSerializer
from django.core.paginator import Paginator
from django.views.generic import DetailView, ListView
from django.views.generic.base import TemplateView
from django_filters.rest_framework import DjangoFilterBackend
from project.models import Industry
from rest_framework import generics
from rest_framework.filters import OrderingFilter
from rest_framework.pagination import LimitOffsetPagination
from rest_framework.response import Response

from .models import ForInvestor, Software
from .serializers import (
    ForInvestorObjSerializer,
    InterestedRequestSerializer,
    PartnershipRequestSerializer,
)

from seo_tags.mixins import MetaTagTemplateMixin


class SoftwareList(MetaTagTemplateMixin, ListView):
    model = Software
    template_name = "partnership/software.html"
    context_object_name = "objects"

    def get_queryset(self):
        return Software.objects.all()


class SoftwareDetail(MetaTagTemplateMixin, DetailView):
    model = Software
    template_name = "partnership/software_detail.html"


class SoftwareSearch(MetaTagTemplateMixin, ListView):
    model = Software
    template_name = "partnership/software.html"
    context_object_name = "objects"

    def get_queryset(self):
        q = self.request.GET.get("q", None)
        if q:
            return Software.objects.filter(name__icontains=q)
        else:
            return Software.objects.all()

    def get_context_data(self, **kwargs):
        context = super(SoftwareSearch, self).get_context_data(**kwargs)
        context["search_query"] = self.request.GET.get("q", "")
        return context


class ForInvestorsTemplateView(VueTemplateMixin, TemplateView):
    template_name = "partnership/investors.html"

    def get_props(self):
        startups = ForInvestorObjSerializer(ForInvestor.objects.all(), many=True).data
        industries = NameSlugSerializer(Industry.objects.all(), many=True).data

        return {
            "startups": startups[:5],
            "industries": industries,
        }


class ForInvestorsListAPIView(generics.ListAPIView):
    queryset = ForInvestor.objects.all()
    serializer_class = ForInvestorObjSerializer
    pagination_class = LimitOffsetPagination
    filter_backends = (DjangoFilterBackend, OrderingFilter)
    filter_fields = ("amount", "industry")
    ordering = ("-created_at",)
    ordering_fields = ("created_at", "rating", "interested_requests")


class InterestedRequestAPIView(generics.UpdateAPIView):
    queryset = ForInvestor.objects.all()
    serializer_class = InterestedRequestSerializer


class ForInvestorsDetailView(VueTemplateMixin, DetailView):
    template_name = "partnership/investors-detailed.html"
    model = ForInvestor

    def get_props(self):
        startup = self.get_object()

        return {"startupId": startup.id}


class CreatePartnershipRequest(generics.CreateAPIView):
    serializer_class = PartnershipRequestSerializer

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        if not serializer.is_valid():
            return Response(data=serializer.errors, status=400)
        self.perform_create(serializer)

        return Response(status=201)

server/templates/partnership/base.html
{% extends 'base.html' %}
{% load menu_tags vuejs sekizai_tags %}
{% block add_metatags %}
  {% if not seo_tags %}
    <meta name="robots" content="index, follow">
  {% endif %}
{% endblock add_metatags %}
{% block body_style %}
style="background-color: #f2f5f8;"
{% endblock body_style %}
{% block content %}
  <section class="section-top">
    <div class="wrapper">
      <div class="title-wrap">
        <span>For Partners</span>
        {{ menu }}
      </div>
      <div class="categories-wrapper d-flex justify-content-between align-items-center">
        <div class="categories-list d-flex justify-content-between align-items-end">
          {% show_menu 1 %}
        </div>
      </div>
    </div>
  </section>

  {% block partnership_content %}{% endblock partnership_content %}
  {% addtoblock "js" %}
    <div id="partnership-modal"></div>
    {% render_component "PartnershipModal" el="partnership-modal" %}
  {% endaddtoblock %}
{% endblock content %}

server/templates/partnership/business_projects.html
{% extends 'partnership/base.html' %}
{% load cms_tags static vuejs sekizai_tags staticfiles %}

{% block partnership_content %}
    <section class="section-about">
        <div class="wrapper">
            <div class="banner">
                <img src="{% static 'images/partner-business-1.jpg' %}" alt="" class="img-fluid">
                {% placeholder 'image_title' %}
            </div>
            <div class="about-info-wrapper" id="acc-finance">
                <div class="row">
                    <div class="col-lg-6 col-md-4">
                        {% placeholder 'text_block_1_title' %}
                    </div>
                    <div class="col-lg-6 col-md-8">
                        {% placeholder 'text_block_1_text' %}
                        <span class="btn-site" data-toggle="modal" data-target="#partnership-modal">Send request</span>
                    </div>
                </div>
            </div>
            <div class="about-info-wrapper" style="padding-top: 0;">
                <div class="banner banner-content">
                    <img src="{% static 'images/partner-business-2.jpg' %}" class="img-fluid" alt="">
                    <div class="banner-content-wrap">
                        {% placeholder 'review' %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

server/templates/partnership/commercial.html
{% extends 'partnership/base.html' %}
{% load cms_tags static vuejs sekizai_tags staticfiles %}

{% block partnership_content %}
    <section class="section-about">
        <div class="wrapper">
            <div class="banner">
                <img src="{% static 'images/partner-commercial-1.jpg' %}" alt="" class="img-fluid">
                {% placeholder 'image_title' %}
            </div>
            <div class="about-info-wrapper" id="acc-finance">
                <div class="row">
                    <div class="col-lg-6 col-md-4">
                        {% placeholder 'text_block_1_title' %}
                    </div>
                    <div class="col-lg-6 col-md-8">
                        {% placeholder 'text_block_1_text' %}
                        <span class="btn-site" data-toggle="modal" data-target="#partnership-modal">Send request</span>
                    </div>
                </div>
            </div>
            <div class="about-info-wrapper" style="padding-top: 0;">
                <div class="banner banner-content">
                    <img src="{% static 'images/partner-commercial-2.jpg' %}" class="img-fluid" alt="">
                    <div class="banner-content-wrap">
                        {% placeholder 'review' %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

server/templates/partnership/consulting.html
{% extends 'partnership/base.html' %}
{% load cms_tags static staticfiles %}

{% block partnership_content %}
    <section class="section-about">
        <div class="wrapper">
            <div class="banner">
                <img src="{% static 'images/partnership/partner-img1.61c8d69.png' %}" alt="" class="img-fluid">
                {% placeholder 'image_title' %}
            </div>
            <div class="about-info-wrapper">
                {% placeholder 'text_block_header' %}
            </div>
            <div class="banner">
                <img src="{% static 'images/partner-consulting-2.jpg' %}" class="img-fluid" alt="">
            </div>
            <div class="about-info-wrapper" id="acc-finance">
                <div class="row">
                    <div class="col-lg-6 col-md-4">
                        {% placeholder 'text_block_1_title' %}
                    </div>
                    <div class="col-lg-6 col-md-8">
                        {% placeholder 'text_block_1_text' %}
                        <span class="btn-site" data-toggle="modal" data-target="#partnership-modal">Send request</span>
                    </div>
                </div>
            </div>
            <div class="banner">
                <img src="{% static 'images/partner-consulting-3.jpg' %}" class="img-fluid" alt="">
            </div>
            <div class="about-info-wrapper" id="legal">
                <div class="row">
                    <div class="col-lg-6 col-md-4">
                        {% placeholder 'text_block_2_title' %}
                    </div>
                    <div class="col-lg-6 col-md-8">
                        {% placeholder 'text_block_2_text' %}
                        <span class="btn-site" data-toggle="modal" data-target="#partnership-modal">Send request</span>
                    </div>
                </div>
            </div>
            <div class="banner">
                <img src="{% static 'images/partner-consulting-4.jpg' %}" class="img-fluid" alt="">
            </div>
            <div class="about-info-wrapper" id="pm">
                <div class="row">
                    <div class="col-lg-6 col-md-4">
                        {% placeholder 'text_block_3_title' %}
                    </div>
                    <div class="col-lg-6 col-md-8">
                        {% placeholder 'text_block_3_text' %}
                        <span class="btn-site" data-toggle="modal" data-target="#partnership-modal">Send request</span>
                    </div>
                </div>
            </div>
            <div class="about-info-wrapper" style="padding-top: 0;">
                <div class="banner banner-content">
                    <img src="{% static 'images/partner-consulting-5.jpg' %}" class="img-fluid" alt="">
                    <div class="banner-content-wrap">
                        {% placeholder 'review' %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

server/templates/partnership/coworking.html
{% extends 'partnership/base.html' %}
{% load cms_tags static vuejs sekizai_tags staticfiles %}

{% block partnership_content %}
    <section class="section-about">
        <div class="wrapper">
            <div class="banner">
                <img src="{% static 'images/partner-coworking-1.jpg' %}" alt="" class="img-fluid">
                {% placeholder 'image_title' %}
            </div>
            <div class="about-info-wrapper" id="acc-finance">
                <div class="row">
                    <div class="col-lg-6 col-md-4">
                        {% placeholder 'text_block_1_title' %}
                    </div>
                    <div class="col-lg-6 col-md-8">
                        {% placeholder 'text_block_1_text' %}
                        <span class="btn-site" data-toggle="modal" data-target="#partnership-modal">Send request</span>
                    </div>
                </div>
            </div>
            <div class="about-info-wrapper" style="padding-top: 0;">
                <div class="banner banner-content">
                    <img src="{% static 'images/partner-coworking-2.jpg' %}" class="img-fluid" alt="">
                    <div class="banner-content-wrap">
                        {% placeholder 'review' %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

server/templates/partnership/investors-detailed.html
{% extends 'partnership/base.html' %}
{% load vuejs sekizai_tags %}

{% block content %}
<section class="section-top article-top">
  <!-- This block needs for to gradient on header -->
</section>
<article class="article-wrapper">
  <div class="wrapper">

    {% url 'blog-list' as back_url %}
    {% include "includes/back-button.html" with text=object.name class="back-to-wrapper" url=back_url %}

    {% autoescape off %}
    {{ object.text }}
    {% endautoescape %}

    <div class="learn-more-button text-center">
      <span class="btn-site" data-toggle="modal" data-target="#interested-modal">I was interested in the project</span>
    </div>
    <div id="interested"></div>

    {% addtoblock "js" %}
    {% render_component "InterestedModal" el="interested" data=data %}
    {% endaddtoblock %}

  </div>
</article>
{% endblock content %}

server/templates/partnership/investors.html
{% extends 'partnership/base.html' %}
{% load cms_tags static vuejs sekizai_tags staticfiles sass_tags %}

{% block partnership_content %}
  {% addtoblock "css" %}
    <link href="{% sass_src 'scss/_partnership.scss' %}"  rel="stylesheet" type="text/css" />
  {% endaddtoblock %}

  <div id="investor-content"></div>

  {% addtoblock "js" %}
  {% render_component "ForInvestors" el="investor-content" data=data %}
  {% endaddtoblock %}
{% endblock %}

server/templates/partnership/software.html
{% extends 'partnership/base.html' %}
{% load cms_tags static vuejs sekizai_tags staticfiles %}

{% block partnership_content %}
    <section class="section-about">
        <div class="wrapper">
            <div class="banner">
                <img src="{% static 'images/partner-software-1.jpg' %}" alt="" class="img-fluid">
                {% placeholder 'image_title' %}
            </div>
            <div class="about-info-wrapper" id="acc-finance">
                <div class="row">
                    <div class="col-lg-6 col-md-4">
                        {% placeholder 'text_block_1_title' %}
                    </div>
                    <div class="col-lg-6 col-md-8">
                        {% placeholder 'text_block_1_text' %}
                    </div>
                </div>
            </div>
            <div class="about-info-wrapper">
                <div class="row">
                    <div class="col-lg-3 col-md-4">
                        <h2 class="about-title">Search software</h2>
                    </div>
                    <div class="col-lg-9 col-md-8">
                        <div class="software-search">
                            <form action="{% url 'software_search' %}" method="get">
                                <input type="search" placeholder="Type name software" name="q" value="{{ search_query }}">
                                <button type="submit">
                                    <span class="mdi mdi-magnify"></span>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="software-solutions">
                <span class="software-title">Popular solutions</span>
                <div class="row flex-wrap">
                    {% for obj in objects %}
                        <div class="col-md-6">
                            <a href="{% url 'software_detail' obj.pk %}" class="software-col d-flex">
                                <div class="software-logo">
                                    <img src="{{ obj.logo.url }}" alt="">
                                </div>
                                <div class="software-info d-flex flex-column justify-content-between">
                                    <div class="software-info-top">
                                        <span class="software-info-title">{{ obj.name }}</span>
                                    </div>
                                    <div class="software-info-bottom d-flex">
                                        <div class="software-info-bottom-col">
                                            <span>Size</span>
                                            <i>{{ obj.size }}</i>
                                        </div>
                                        <div class="software-info-bottom-col">
                                            <span>License</span>
                                            <i>free</i>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

server/templates/partnership/software_detail.html
{% extends 'partnership/base.html' %}
{% load cms_tags staticfiles vuejs sekizai_tags staticfiles %}

{% block partnership_content %}
    <section class="section-about">
        <div class="wrapper">
            <div class="about-info-wrapper" style="padding-top: 0;">
                <div class="row">
                    <div class="col-lg-6 col-md-4">
                        <div class="back-to-wrapper">
                            <a href="{% url 'software' %}"><span class="mdi mdi-arrow-left"></span> {{ object.name }}</a>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-8">
                        <p class="about-description">SOLIDWORKS Product Data Management (PDM) solutions help you get your design data under control and substantially improve the way your teams manage and collaborate on product development.</p>
                    </div>
                </div>
            </div>
            <div class="banner">
                <img src="{{ object.image.url }}" class="img-fluid" alt="">
            </div>
            <div class="about-info-wrapper">
                <p class="about-description text-center">
                    {{ object.short_description | safe }}
                </p>
            </div>
            <div class="software-solutions">
                <div class="row flex-wrap">
                    <div class="col-md-12">
                        <div class="software-col d-flex">
                            <div class="software-logo">
                                <img src="{{ object.logo.url }}" alt="">
                            </div>
                            <div class="software-info d-flex flex-column justify-content-between">
                                <div class="software-info-top">
                                    <span class="software-info-title">{{ object.name }}</span>
                                    <p>
                                        {{ object.description | safe }}
                                    </p>
                                </div>
                                <div class="d-flex justify-content-between align-items-center flex-wrap">
                                    <div class="software-info-bottom d-flex align-items-center flex-wrap">
                                        <div class="software-info-bottom-col">
                                            <span>Size</span>
                                            <i>{{ object.size }}</i>
                                        </div>
                                        <div class="software-info-bottom-col">
                                            <span>License</span>
                                            <i>free</i>
                                        </div>
                                        <div class="software-info-bottom-col d-flex">
                                            <img src="{% static 'images/apple.svg' %}" alt="">
                                            <img src="{% static 'images/windows.svg' %}" alt="">
                                            <img src="{% static 'images/linux.svg' %}" alt="">
                                        </div>
                                    </div>

                                    <div class="dropdown software-dropdown">
                                        <button type="button" class="download-button" data-toggle="dropdown">
                                            <mark>Download <span class="mdi mdi-menu-down"></span></mark>
                                        </button>
                                        <div class="dropdown-menu">
                                            {% for os in object.software_file.all %}
                                                <a target="_blank" class="dropdown-item" href="{{ os.file.url }}">{{ os.get_os_display }}</a>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}